server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
  port: ${PORT:8080}

spring:
  application:
    name: poker-game-service

  output:
    ansi.enabled: always

  datasource:
    url: jdbc:h2:mem:poker-planning-service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: username
    password: password
    driverClassName: org.h2.Driver

    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: none
      open-in-view: true
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true

    h2:
      console:
        enabled: true


app:
  firebase-configuration-file: firebase-service-account.json